name: Generate Snake Contribution Graph

on:
  # Trigger the workflow on push or manually
  push:
    branches:
      - main
  schedule:
    # Run at 12am UTC daily
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Use the Platane/snk action to generate the snake graph
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 3: Push the generated files to the repository
      - name: Commit and Push Generated Files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated GitHub Contribution Snake 🐍"
          file_pattern: dist/*
